# Generated by Django 4.2.16 on 2025-03-15 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Trading Rules'), ('DAILY', 'Daily Reminders'), ('PSYCH', 'Psychological Insights')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('trade_type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('OPTION', 'Options')], max_length=10)),
                ('ticker_symbol', models.CharField(max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_win', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('execution_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rules_followed', models.ManyToManyField(blank=True, related_name='trades', to='trading_journal.traderule')),
                ('tags', models.ManyToManyField(related_name='trades', to='trading_journal.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
