# Generated by Django 4.2.16 on 2025-03-16 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_journal', '0003_tag_color_tagcategory_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_size',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('OPTION', 'Options')], max_length=10),
        ),
    ]
